### ISSUE TITLE
Not Use this lib

### ISSUE THREAD

**Issue by tellfa** [madcyph3r/AdvancedMaterialDrawer#23]
hi, thanks you for develop for this lib
i want use this lib but i'm not. run of the project show me this errors : 

03-31 12:42:54.427    2130-2130/com.example.tellfa.myapplication4 E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.example.tellfa.myapplication4, PID: 2130
    java.lang.NoSuchFieldError: de.madcyph3r.materialnavigationdrawer.R$id.current_head_item_title
            at de.madcyph3r.materialnavigationdrawer.MaterialNavigationDrawer.initViews(MaterialNavigationDrawer.java:300)
            at de.madcyph3r.materialnavigationdrawer.MaterialNavigationDrawer.onCreate(MaterialNavigationDrawer.java:184)
            at android.app.Activity.performCreate(Activity.java:5231)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
            at android.app.ActivityThread.access$800(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)

please help me, this lib is important for me

**Comment by madcyph3r** [comment]
Try to clean your project. It can't finds an id from a layout. Normally you get this problem, when your project has errors on building. After you fix this, the R class get build right.

How do you import this Library?

**Comment by tellfa** [comment]
I have added this in Gradle file
 repositories {
    maven { url 'http://dl.bintray.com/madcyph3r/maven/' }
}
dependencies {
    compile 'de.madcyph3r:materialDrawer:1.1.1@aar'
}

my MainActivity codes has below link, please see it
code link : http://dl.tellfa.com/Online_Course/MainActivity.txt

**Comment by madcyph3r** [comment]
In your MainActivity.txt, you have forgotten a closing bracket at the end.

**Comment by tellfa** [comment]
added end bracket bud Fc when running. please help . i need it :(

**Comment by madcyph3r** [comment]
Have you cleaned your project. 
Other idea, try to download the example project and replace the code from the main activity with yours and see if it runs. When yes, something is misconfigured.

**Comment by tellfa** [comment]
Is it possible to upload my project and you are correct, and that I am using?
i want use this lib to MainActivity, my MainActivity has onCreate() method.
Can I upload my project?

**Comment by madcyph3r** [comment]
You can't us the onCreate() method, you must use the init() mehtod. But you can send me your project to mad.cyph3r@gmail.com , i will correct it.

**Comment by tellfa** [comment]
thanks you to help me.
you are amazing my friend <3
