### ISSUE TITLE
Crashes on API 10

### ISSUE THREAD

**Issue by JerabekJakub** [madcyph3r/AdvancedMaterialDrawer#65]
Hi Marc, we have tested our application on customer's required minimal API 10 and your library keeps crashing. To be specific, it is device with Android 2.3.6. 

Exception:

```
    java.lang.NoSuchMethodError: android.view.View.setTranslationX
            at de.madcyph3r.materialnavigationdrawer.custom.DefaultDrawerListener.onDrawerSlide(DefaultDrawerListener.java:29)
            at de.madcyph3r.materialnavigationdrawer.MaterialNavigationDrawer$2.onDrawerSlide(MaterialNavigationDrawer.java:371)
            at android.support.v4.widget.DrawerLayout.dispatchOnDrawerSlide(DrawerLayout.java:701)
            at android.support.v4.widget.DrawerLayout.setDrawerViewOffset(DrawerLayout.java:712)
            at android.support.v4.widget.DrawerLayout$ViewDragCallback.onViewPositionChanged(DrawerLayout.java:1671)
```

The reason is quite obvious, you are calling method setTranslationX() which has been added in API 11.
Would it be possible to fix it? Thank you in advance.

**Comment by madcyph3r** [comment]
https://github.com/madcyph3r/AdvancedMaterialDrawer/blob/master/materialDrawer/src/main/java/de/madcyph3r/materialnavigationdrawer/custom/DefaultDrawerListener.java

make on line 29 this if:
if(Build.VERSION.SDK_INT >= 11 ) 

before drawerView.setTranslationX(widthdrawer \* slideOffset);

I can add it next week, I have no time at the moment.
